### ISSUE TITLE
All-in 기능 추가해주세요.

### ISSUE THREAD

**Issue by Heo-H** [answprkdltek/11_project#13]
만약 내가 가진 돈이 기본 배팅금액 이하일 경우, all-in 되도록 해주세요.

**Comment by sjyoo1699** [comment]
이 기능을 구현하는 데 있어서, 기본 배팅금액이라는 것이 +-  버튼을 눌렀을 때, 올라가는 금액이라면 별 의미가 없는 기능인 것 같아서, 최소 배팅금액이라고 생각을 하고 구현을 해야할 것 같습니다.
따라서, 최소 배팅금액 기능을 구현해야할 것 같습니다.
