### ISSUE TITLE
최소 배팅 금액이 필요할 것 같습니다.

### ISSUE THREAD

**Issue by sjyoo1699** [answprkdltek/11_project#30]
All-in 기능을 구현하기 위해 최소 배팅 금액이 필요할 것 같습니다.

**Comment by sjyoo1699** [comment]
서버 사이드에서도 확인을 해야 할 지 팀원분들의 의견 부탁드립니다.

**Comment by Heo-H** [comment]
상한선도 확인하므로, 하한선도 확인 해야될 것 같습니다.

**Comment by answprkdltek** [comment]
확인이 필요하다고 생각합니다.

**Comment by answprkdltek** [comment]
설마 안하려고 함? 이거 직무유기

**Comment by mtjin** [comment]
해야할것 같습니다.
