### ISSUE TITLE
게임이 끝났는데도 DB에 반영이 안됩니다.

### ISSUE THREAD

**Issue by answprkdltek** [answprkdltek/11_project#7]
같은 아이디로 다음 번에 접속 시, 잃었거나 땄던 돈이 DB에 반영되지 않고 reset됩니다.
DB에 반영되도록 고쳐야 합니다.

**Comment by Heo-H** [comment]
해당 이슈를 해결하던 중에 DB 업데이트 작업을 어느 객체가 수행할지 고민을 했습니다.
팀원들과 상의한 결과, MVC 패턴에 따라 DB에 접근하는 객체를 Controller에서 Service로 변경해야한다고 결론을 내렸습니다.
